### PR TITLE
Fix `fopen(filename, "a")` misinterpreted as `fopen(filename, "w")`

### LINKED ISSUE #353: fopen(filename, "a") truncates?
Looking at the code:

```c
static unsigned filemode(const char *const mode) {
  unsigned rc = 0;

  switch (mode[0]) {
  case 'r':
    rc |= FREAD;
    break;

  case 'w':
    rc |= FWRITE;
    break;

  case 'a':
    rc |= FAPPEND | FWRITE;
    break;
  }
```

```c
static signed char stdio_open(const char *const filename, unsigned int mode) {
  int osmode;

  if (mode & FRW)
    osmode = O_RDWR;
  else if (mode & FREAD)
    osmode = O_RDONLY;
  else
    osmode = O_WRONLY;

  if (mode & (FWRITE | FAPPEND))
    osmode |= O_CREAT;

  if (mode & FWRITE)
    osmode |= mode & FEXCL ? O_EXCL : O_TRUNC;
  else if (mode & FAPPEND)
    osmode |= O_APPEND;
```

`"a"` will set `O_TRUNC` i.e. truncate an existing file.
I think we should either not set `FWRITE` or reorganize the logic in `stdio_open`.

### PR DESCRIPTION
**Pull request by pfusik**
Fix #353

### CODE REVIEW

File: mos-platform/common/c/stdio-full.c [hunk 1]
```diff
@@ -169,12 +169,15 @@ static signed char stdio_open(const char *const filename, unsigned int mode) {
...
 
   if (mode & (FWRITE | FAPPEND))
-    osmode |= O_CREAT;
+    osmode |= O_CREAT;    // file doesn't exist: create
 
-  if (mode & FWRITE)
-    osmode |= mode & FEXCL ? O_EXCL : O_TRUNC;
-  else if (mode & FAPPEND)
-    osmode |= O_APPEND;
+  if (mode & FAPPEND)
```
Comment (mysterymath) [inline mos-platform/common/c/stdio-full.c:174]: nit: braces around `if` clause if `else` clause has them

**Review by mysterymath — APPROVED** [review]
LGTM; thanks!

File: mos-platform/common/c/stdio-full.c (hunk 1 above)
Comment (pfusik) [reply mos-platform/common/c/stdio-full.c]: Done
